########################################################################
#  This file is provided under a dual BSD/GPLv2 license.  When using or
#  redistributing this file, you may do so under either license.
#
#  GPL LICENSE SUMMARY
#  Copyright(c) 2019 Intel Corporation.
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  Contact Information:
#  qat-linux@intel.com
#
#  BSD LICENSE
#  Copyright(c) 2019 Intel Corporation.
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#    * Neither the name of Intel Corporation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
########################################################################
# Kbuild file for out-of-tree driver only !!!DO NOT PUSH UPSTREAM!!!
include $(src)/Makefile

intel_qat-objs += ../../../../compat/qat_compat.o

ifneq ($(QAT_NO_LKCF),y)
intel_qat-objs += qat_algs_old.o \
	qat_asym_algs_old.o \
	qat_rsapubkey-asn1.o \
	qat_rsaprivkey-asn1.o
endif

intel_qat-$(QAT_UIO) += \
	adf_uio.o \
	adf_uio_control.o \
	adf_uio_cleanup.o \
	adf_dev_processes.o \
	qdm.o \
	adf_cfg_device.o \
	adf_cfg_bundle.o \
	adf_cfg_instance.o \
	adf_cfg_section.o \
	adf_sla.o \
	adf_du.o \
	adf_ctl_rl.o

ccflags-$(QAT_UIO) += -DQAT_RSA_SUPPORT=y -DQAT_AEAD_OLD_SUPPORT=y
ccflags-$(ICP_HB_FAIL_SIM) += -DQAT_HB_FAIL_SIM=y
ifdef KPT
intel_qat-$(QAT_UIO) += adf_mei_kpt.o
endif
ccflags-$(QAT_PKE_MAX_SZ_SIGN) += -DQAT_PKE_MAX_SZ_SIGN=""
ccflags-$(QAT_PKE_MAX_SZ_UNSIGN) += -DQAT_PKE_MAX_SZ_SIGN=unsigned
